# Site Settings
baseurl: ""
url: "https://altaysimsek.github.io"

# Blog Settings
theme_settings:
    title: Altay Simsek
    favicon: assets/favicon.ico

    # Profile Settings
    profile:
        image: assets/img/altay.jpg
        username: Altay Simsek
        description: 20 years old computer science student at Pamukkale University and want to be frontend developer.
        experience:
            # - start : 2017-05-03
            #   end : 2018-05-06
            #   experience : company name, title
        skills:
            # - skill : HTML5 & CSS
            #   value : 85  # Percent value

    # Icons
    icons:
        email: "altaysimsek16@gmail.com" # Full email address, e.g. "sample@google.com"
        linkedin: "https://www.linkedin.com/in/altaysimsek/" # Full URL
        github: altaysimsek
        gitlab:
        bitbucket:
        google_plus:
        twitter: altitans
        youtube:
        facebook:
        instagram:

    # Disqus
    disqus_shortname:

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
    sass_dir: _sass
    style: :compressed
gems: [jekyll-paginate]
bootstrap:
    assets: true
